### ISSUE TITLE
Spark on OpenShift is not running with PVC

### ISSUE THREAD

**Issue by yogeshwariingale** [guimou/spark-on-openshift#6]
Hi, 

I tried spark on openshift with PVC storage instead of s3 bucket, But I am getting below error. 

> failed to run spark-submit for SparkApplication daut-spark-pis-d0/sparkapplication: WARNING: An illegal reflective access operation has occurred\nWARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark/jars/spark-unsafe_2.12-3.1.1.jar) to constructor java.nio.DirectByteBuffer(long,int)\nWARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform\nWARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations\nWARNING: All illegal access operations will be denied in a future release\n23/05/17 16:08:39 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable\nUsing Spark's default log4j profile: org/apache/spark/log4j-defaults.properties\n23/05/17 16:08:39 INFO SparkKubernetesClientFactory: Auto-configuring K8S client using current context from users K8S config file\n23/05/17 16:08:40 INFO KerberosConfDriverFeatureStep: You have not specified a krb5.conf file locally or via a ConfigMap. Make sure that you have the krb5.conf locally on the driver image.\nException in thread \"main\" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.30.0.1/api/v1/namespaces/daut-spark-pis-d0/pods. Message: Pod \"sparkapplication-driver\" is invalid: spec.containers[0].resources.requests: Invalid value: \"1\": must be less than or equal to cpu limit. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.containers[0].resources.requests, message=Invalid value: \"1\": must be less than or equal to cpu limit, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Pod, name=sparkapplication-driver, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Pod \"sparkapplication-driver\" is invalid: spec.containers[0].resources.requests: Invalid value: \"1\": must be less than or equal to cpu limit, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:589)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:528)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:492)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:451)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:252)\n\tat io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:879)\n\tat io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:341)\n\tat io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:84)\n\tat org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:139)\n\tat org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$3(KubernetesClientApplication.scala:213)\n\tat org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$3$adapted(KubernetesClientApplication.scala:207)\n\tat org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2611)\n\tat org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:207)\n\tat org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:179)\n\tat org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)\n\tat org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)\n\tat org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)\n\tat org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)\n\tat org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1030)\n\tat org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1039)\n\tat org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)\n23/05/17 16:08:42 INFO ShutdownHookManager: Shutdown hook called\n23/05/17 16:08:42 INFO ShutdownHookManager: Deleting directory /tmp/spark-1049052c-bfee-475e-98d3-0035225d3f66\n"

**Comment by guimou** [comment]
What's your code?
From the error it seems that the number of CPU you put in the resources is
wrong or badly formatted.

**Comment by guimou** [comment]
Old issue, no answer, closing...
